#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SYMLINK_DIR="$PROJECT_DIR/paperless-consume"
OUTPUT="$PROJECT_DIR/docker-compose.consume.yml"

mkdir -p "$SYMLINK_DIR"

entries=()
for item in "$SYMLINK_DIR"/*; do
    [ -e "$item" ] || [ -L "$item" ] || continue
    base="$(basename "$item")"
    if [ -L "$item" ]; then
        target="$(readlink "$item")"
        case "$target" in
            /*) real="$target" ;;
            *)  real="$(cd "$(dirname "$item")" && cd "$target" && pwd)" ;;
        esac
        entries+=("$base" "$real")
    fi
done

if [ ${#entries[@]} -eq 0 ]; then
    rm -f "$OUTPUT"
    exit 0
fi

{
    echo '# Auto-generated by scripts/generate-consume-override.sh'
    echo '# DO NOT EDIT — re-run make prepare to regenerate.'
    echo 'services:'
    echo '  paperless:'
    echo '    volumes:'
    i=0
    while [ $i -lt ${#entries[@]} ]; do
        name="${entries[$i]}"
        path="${entries[$((i+1))]}"
        printf '      - "%s:/usr/src/paperless/consume/%s"\n' "$path" "$name"
        i=$((i+2))
    done
} > "$OUTPUT"

echo "Generated $OUTPUT with $(( ${#entries[@]} / 2 )) mount(s)"
